//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnewm
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistratioNabor
    {
        public int Registration_id { get; set; }
        public string Name { get; set; }
        public string E_mail { get; set; }
    }
}
